---
title: "R Notebook"
output: html_notebook
---
# Identify most popular Greenwich Village restaurants from comment thread on NextDoor

```{r}
library(rvest)
library(tidyverse)
library(tidytext)
```

```{r}
comment_html <- read_html("data/resto_comments.html")
comments <- comment_html %>% 
  html_nodes("span.Linkify") %>% 
  html_text() %>% 
  enframe(name=NULL,value="comment")
```

```{r}
#clean up
comments <- comments %>% mutate(comment=str_replace_all(comment,"&","and"))

unigrams <- comments %>% unnest_tokens(token,comment,token = "ngrams",n=1)
bigrams <- comments %>% unnest_tokens(token,comment,token = "ngrams",n=2)
trigrams <- comments %>% unnest_tokens(token,comment,token = "ngrams",n=3)

#filter stop words in unigrams
unigrams <- unigrams %>%
  filter(!token %in% stop_words$word)

trigrams <- trigrams %>% group_by(token) %>% summarize(freq=n()) %>% arrange(desc(freq))
bigrams  <- bigrams %>% group_by(token) %>% summarize(freq=n()) %>% arrange(desc(freq))
unigrams <- unigrams %>% group_by(token) %>% summarize(freq=n()) %>% arrange(desc(freq))
ranked_terms <- bind_rows(trigrams,bigrams,unigrams) %>% arrange(desc(freq)) %>% mutate(is_rest="n")

```
```{r}
#manually flag restaurants
ranked_rests <- edit(ranked_terms)
```

```{r}
ranked_rests <- ranked_rests %>% filter(is_rest=="y")
ranked_rests <- edit(ranked_rests)
ranked_rests %>% filter(freq > 0) %>% select(-is_rest) %>% arrange(desc(freq))
write_csv(ranked_rests,"data/ranked_rests.csv")
```
